### ISSUE TITLE
XODX Application error

### ISSUE THREAD

**Issue by NathanielOye** [AKSW/xodx#47] opened 2015-03-20 11:41 UTC
Unbound Prefix: sioc in Parser.php@l.1758

**Comment by white-gecko** [comment] 2015-03-20 13:14
In which context do you get this error? Are you importing a WebID, which might not have all prefixes set?

**Comment by NathanielOye** [comment] 2015-03-20 13:18
No sir.
We were just trying to deploy XODX application. We have being making efforts to at least see the first page come up. But uptil now, no page has being successfully viewed.
Kindly help sir. 

Thank you.

```
 On Friday, March 20, 2015 6:15 AM, Natanael Arndt <notifications@github.com> wrote:
```

 In which context do you get this error? Are you importing a WebID, which might not have all prefixes set?—

**Comment by white-gecko** [comment] 2015-03-20 13:20
Ok, this issue is just fixed in 6a3f0814924bcaa77e488387751741e97ef49afe i forgot to declare the prefix in a sparql query. Please check out the latest development branch.

**Closed as completed by white-gecko** 2015-03-20 13:20 UTC

**Comment by NathanielOye** [comment] 2015-03-20 13:33
Thank you sir, it worked!
However, as we progress, we encountered similar error again.

Application Error
 Unbound Prefix: foaf in Parser.php@l.1758    
- Parser.php@l.1217
- Parser.php@l.1671
- Parser.php@l.1084
- Parser.php@l.1716
- Parser.php@l.1437
- Parser.php@l.330
- EfZendDb.php@l.1110
- Store.php@l.1617
- Model.php@l.656
- UserController.php@l.247
- IndexController.php@l.12
- Application.php@l.45
- index.php@l.64

Please bear with us. Thank you. 

```
 On Friday, March 20, 2015 6:20 AM, Natanael Arndt <notifications@github.com> wrote:
```

 Ok, this issue is just fixed in 6a3f081 i forgot to declare the prefix in a sparql query. Please check out the latest development branch.—

**Comment by white-gecko** [comment] 2015-03-20 13:46
Ok, this was a follow-up issue caused by a typo. Please update source.

**Comment by NathanielOye** [comment] 2015-03-20 13:50
Sorry sir, not clear about this explanation. Can kindly shed more light?
Thank you sir.

```
 On Friday, March 20, 2015 6:46 AM, Natanael Arndt <notifications@github.com> wrote:
```

 Ok, this was a follow-up issue caused by a typo. Please update source.—

**Comment by white-gecko** [comment] 2015-03-20 14:06
Please checkout the latest development branch.

**Comment by NathanielOye** [comment] 2015-03-20 14:32
Alright sir. That is if I get you right, you meant that I should download another XODX from GitHub?

```
 On Friday, March 20, 2015 7:06 AM, Natanael Arndt <notifications@github.com> wrote:
```

 Please checkout the latest development branch.—
